
/* File generated by gen_cfile.py. Should not be modified. */

#include <dict.h>

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 TestMaster_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 TestMaster_bDeviceNodeId = 0xFF;

/**************************************************************************/
/* Array of message processing information */

const UNS8 TestMaster_iam_a_slave = 0;

TIMER_HANDLE TestMaster_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 TestMaster_obj1000 = 0x0;	/* 0 */
                    subindex TestMaster_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1000, NULL }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 TestMaster_obj1001 = 0x0;	/* 0 */
                    subindex TestMaster_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_obj1001, NULL }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 TestMaster_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex TestMaster_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1003, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1003[0], NULL }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 TestMaster_obj1005 = 0x40000080 ;   /* start 0x40000080*/

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 TestMaster_obj1006 = 0xC350;   /* 0x10000us 0x2710  1s 0xF4240*/

/* index 0x100C :   Guard Time */ 
                    UNS16 TestMaster_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 TestMaster_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 TestMaster_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 TestMaster_highestSubIndex_obj1016 = 0;
                    UNS32 TestMaster_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 TestMaster_obj1017 = 0x0;	/* 0x1000ms 0x3E8 */
                    subindex TestMaster_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1017, NULL }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 TestMaster_highestSubIndex_obj1018 = 4; /* umber of subindex - 1*/
                    UNS32 TestMaster_obj1018_Vendor_ID = 0x33333333;
                    UNS32 TestMaster_obj1018_Product_Code = 0x22222222;
                    UNS32 TestMaster_obj1018_Revision_Number = 0x11111111;
                    UNS32 TestMaster_obj1018_Serial_Number = 0x12345678;
                    subindex TestMaster_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1018, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1018_Vendor_ID, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1018_Product_Code, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1018_Revision_Number, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1018_Serial_Number, NULL }
                     };
										 
/* index 0x1200 :   SDO server parameter.     Index 1200h-127Fh，Sever SDO Parameter，1200h可选*/
					UNS8 ServerNumber_0x1200 = 2;
					UNS32 TestMaster_obj1200_COB_ID_SDO_CS_RX  = 0x600;
                    UNS32 TestMaster_obj1200_COB_ID_SDO_SC_TX = 0x580;
					subindex TestMaster_Index1200[] = 
					{
                       { RO, uint8, sizeof (UNS8), (void*)&ServerNumber_0x1200, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1200_COB_ID_SDO_CS_RX, NULL },
						{ RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1200_COB_ID_SDO_SC_TX, NULL },
					};
									 
/* index 0x1280 :   SDO clit .    Index 1280h-12FFh，Client SDO Parameter，必须如果支持对应的Client SDO  
										 当我需要配置其他节点的字典值时，我变成了客户端，要求服务器自己修改自己*/ 
					#define Node 2
					UNS8 ClientNumber_0x1280 = 3;
					UNS32 TestMaster_obj1280_COB_ID_SDO_CS_TX  = 0x600 + Node;
					UNS32 TestMaster_obj1280_COB_ID_SDO_SC_RX = 0x580 + Node;
					UNS8 TestMaster_obj1280_COB_ID_Server = Node;//服务器，也就是需要修改的节点
                    subindex TestMaster_Index1280[] = 
                     {
						{ RO, uint8,  sizeof (UNS8), (void*)&ClientNumber_0x1280, NULL },
						{ RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1280_COB_ID_SDO_CS_TX, NULL },
						{ RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1280_COB_ID_SDO_SC_RX, NULL },
						{ RO, uint8,  sizeof (UNS8), (void*)&TestMaster_obj1280_COB_ID_Server, NULL },
                     };

/* index 0x1281 :   SDO clit .    Index 1280h-12FFh，Client SDO Parameter，必须如果支持对应的Client SDO
										 当我需要配置其他节点的字典值时，我变成了客户端，要求服务器自己修改自己*/
					UNS8 ClientNumber_0x1281 = 3;
					UNS32 TestMaster_obj1281_COB_ID_SDO_CS_TX  = 0x603;
					UNS32 TestMaster_obj1281_COB_ID_SDO_SC_RX = 0x583;
					UNS8 TestMaster_obj1281_COB_ID_Server = 3;//服务器，也就是需要修改的节点
					subindex TestMaster_Index1281[] =
					 {
						{ RO, uint8,  sizeof (UNS8), (void*)&ClientNumber_0x1281, NULL },
						{ RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1281_COB_ID_SDO_CS_TX, NULL },
						{ RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1281_COB_ID_SDO_SC_RX, NULL },
						{ RO, uint8,  sizeof (UNS8), (void*)&TestMaster_obj1281_COB_ID_Server, NULL },
					 };


/* index 0x1400 :   RPDO 1 parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1400 = 2; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1400_COB_ID  = 0x00000200;
                    UNS8 TestMaster_obj1400_Transmission_type = TRANS_EVERY_N_SYNC(1);
                    subindex TestMaster_Index1400[] = 
                     {
                       { RO, uint8, 	sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1400, NULL },
                       { RW, uint32, 	sizeof (UNS32), (void*)&TestMaster_obj1400_COB_ID, NULL },
                       { RO, uint8, 	sizeof (UNS8), (void*)&TestMaster_obj1400_Transmission_type, NULL },
                     };
										 
/* index 0x1401 :   RPDO 2 parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1401 = 2; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1401_COB_ID  = 0x000;
                    UNS8 TestMaster_obj1401_Transmission_type = TRANS_EVERY_N_SYNC(1);
                    subindex TestMaster_Index1401[] = 
                     {
                       { RO, uint8, 	sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1401, NULL },
                       { RW, uint32, 	sizeof (UNS32), (void*)&TestMaster_obj1401_COB_ID, NULL },
                       { RO, uint8, 	sizeof (UNS8), (void*)&TestMaster_obj1401_Transmission_type, NULL },
                     };
										 
/* index 0x1402 :   RPDO 3 parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1402 = 5; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1402_COB_ID  = 0x000;
                    UNS8 TestMaster_obj1402_Transmission_type = 0x000;
										UNS16 TestMaster_obj1402_inhibit_time = 0x00;
										UNS8 TestMaster_obj1402_compatibility_entry = 0x00;
										UNS16 TestMaster_obj1402_event_time = 0x00;
                    subindex TestMaster_Index1402[] = 
                     {
                       { RO, uint8, 	sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1402, NULL },
                       { RO, uint32, 	sizeof (UNS32), (void*)&TestMaster_obj1402_COB_ID, NULL },
                       { RO, uint8, 	sizeof (UNS8), (void*)&TestMaster_obj1402_Transmission_type, NULL },
                       { RO, uint16, 	sizeof (UNS16), (void*)&TestMaster_obj1402_inhibit_time, NULL },
                       { RO, uint8, 	sizeof (UNS8), (void*)&TestMaster_obj1402_compatibility_entry, NULL },
											 { RO, uint16, 	sizeof (UNS16), (void*)&TestMaster_obj1402_event_time, NULL }
                     };

/* index 0x1403 :   RPDO 4 parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1403 = 5; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1403_COB_ID  = 0x000;
                    UNS8 TestMaster_obj1403_Transmission_type = 0x000;
										UNS16 TestMaster_obj1403_inhibit_time = 0x00;
										UNS8 TestMaster_obj1403_compatibility_entry = 0x00;
										UNS16 TestMaster_obj1403_event_time = 0x00;
                    subindex TestMaster_Index1403[] = 
                     {
                       { RO, uint8, 	sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1403, NULL },
                       { RO, uint32, 	sizeof (UNS32), (void*)&TestMaster_obj1403_COB_ID, NULL },
                       { RO, uint8, 	sizeof (UNS8), (void*)&TestMaster_obj1403_Transmission_type, NULL },
                       { RO, uint16, 	sizeof (UNS16), (void*)&TestMaster_obj1403_inhibit_time, NULL },
                       { RO, uint8, 	sizeof (UNS8), (void*)&TestMaster_obj1403_compatibility_entry, NULL },
											 { RO, uint16, 	sizeof (UNS16), (void*)&TestMaster_obj1403_event_time, NULL }
                     };

 /* 0x1600	 Index 1600h-17FFh，Receive PDO Mapping Parameter */
					 UNS8 TestMaster_obj1600_Number_mapped = 2; //服务器，也就是需要修改的节点
					 UNS32 TestMaster_obj1600_1_mapped = 0x60410010;
					 UNS32 TestMaster_obj1600_2_mapped = 0x60640020;
					 subindex TestMaster_Index1600[] = 
					 {
						 { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1600_Number_mapped, NULL },
						 { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1600_1_mapped, NULL },
						 { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1600_2_mapped, NULL },
					 };
						 
 /* 0x1601	 Index 1601h-17FFh，Receive PDO Mapping Parameter */
					 UNS8 TestMaster_obj1601_Number_mapped = 1; //服务器，也就是需要修改的节点
					 //UNS32 TestMaster_obj1601_1_mapped = 0x60400010;
					 UNS32 TestMaster_obj1601_2_mapped = 0x60630020;
					 subindex TestMaster_Index1601[] = 
					 {
						 { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1601_Number_mapped, NULL },
						 //{ RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1601_1_mapped, NULL },
						 { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1601_2_mapped, NULL },
					 };
						 
 /* 0x1602	 Index 1602h-17FFh，Receive PDO Mapping Parameter */
					 UNS8 TestMaster_obj1602_Number_mapped = 2; //服务器，也就是需要修改的节点
					 UNS32 TestMaster_obj1602_1_mapped = 0x60400010;
					 UNS32 TestMaster_obj1602_2_mapped = 0x607A0020;
					 subindex TestMaster_Index1602[] = 
					 {
						 { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1602_Number_mapped, NULL },
						 { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1602_1_mapped, NULL },
						 { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1602_2_mapped, NULL },
					 };
						 
 /* 0x1603	 Index 1603h-17FFh，Receive PDO Mapping Parameter */
					 UNS8 TestMaster_obj1603_Number_mapped = 2; //服务器，也就是需要修改的节点
					 UNS32 TestMaster_obj1603_1_mapped = 0x60400010;
					 UNS32 TestMaster_obj1603_2_mapped = 0x607A0020;
					 subindex TestMaster_Index1603[] = 
					 {
						 { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1603_Number_mapped, NULL },
						 { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1603_1_mapped, NULL },
						 { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1603_2_mapped, NULL },
					 };
										 
/* index 0x1800 :   TPDO 1 .    Index 1800h-19FFh,  Transmit PDO Communication Parameter  */ 
					UNS8 ClientNumber_0x1800 = 5;
					UNS32 TestMaster_obj1800_COB_ID_PDO = 0x40000180;//服务器，也就是需要修改的节点
					UNS8 TestMaster_obj1800_Transmiss_Type  = 1;
					UNS16 TestMaster_obj1800_Inhibit_time = 10;
					UNS8 TestMaster_obj1800_compatibility_entry = 0;
					UNS16 TestMaster_obj1800_event_time  = 0;
					subindex TestMaster_Index1800[] = 
					 {
						 { RO, uint8,  sizeof (UNS8), (void*)&ClientNumber_0x1800, NULL },
						 { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1800_COB_ID_PDO, NULL },
						 { RO, uint8, sizeof (UNS8), (void*)&TestMaster_obj1800_Transmiss_Type, NULL },
						 { RW, uint16,  sizeof (UNS16), (void*)&TestMaster_obj1800_Inhibit_time, NULL },
						 { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1800_compatibility_entry, NULL },
						 { RW, uint16,  sizeof (UNS16), (void*)&TestMaster_obj1800_event_time, NULL },
					 };

/* index 0x1801 :   TPDO 2 .    Index 1801h-19FFh,  Transmit PDO Communication Parameter  
										 当我需要配置其他节点的字典值时，我变成了客户端，要求服务器自己修改自己*/ 
					UNS8 ClientNumber_0x1801 = 5;
					UNS32 TestMaster_obj1801_COB_ID_PDO = 0x40000280;//服务器，也就是需要修改的节点
					UNS8 TestMaster_obj1801_Transmiss_Type  = 1;
					UNS16 TestMaster_obj1801_Inhibit_time = 10;
					UNS8 TestMaster_obj1801_compatibility_entry = 0;
					UNS16 TestMaster_obj1801_event_time  = 0;
					subindex TestMaster_Index1801[] = 
					 {
						 { RO, uint8,  sizeof (UNS8), (void*)&ClientNumber_0x1801, NULL },
						 { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1801_COB_ID_PDO, NULL },
						 { RO, uint8, sizeof (UNS8), (void*)&TestMaster_obj1801_Transmiss_Type, NULL },
						 { RW, uint16,  sizeof (UNS16), (void*)&TestMaster_obj1801_Inhibit_time, NULL },
						 { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1801_compatibility_entry, NULL },
						 { RW, uint16,  sizeof (UNS16), (void*)&TestMaster_obj1801_event_time, NULL },
					 };

/* index 0x1802 :   TPDO .    Index 1802h-19FFh,  Transmit PDO Communication Parameter  
										 当我需要配置其他节点的字典值时，我变成了客户端，要求服务器自己修改自己*/ 
					UNS8 ClientNumber_0x1802 = 5;
					UNS32 TestMaster_obj1802_COB_ID_PDO = 0x40000185;//服务器，也就是需要修改的节点
					UNS8 TestMaster_obj1802_Transmiss_Type  = TRANS_EVERY_N_SYNC(1);
					UNS16 TestMaster_obj1802_Inhibit_time = 10;
					UNS8 TestMaster_obj1802_compatibility_entry = 0;
					UNS16 TestMaster_obj1802_event_time  = 0;
					subindex TestMaster_Index1802[] = 
					 {
						 { RO, uint8,  sizeof (UNS8), (void*)&ClientNumber_0x1802, NULL },
						 { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1802_COB_ID_PDO, NULL },
						 { RO, uint8, sizeof (UNS8), (void*)&TestMaster_obj1802_Transmiss_Type, NULL },
						 { RW, uint16,  sizeof (UNS16), (void*)&TestMaster_obj1802_Inhibit_time, NULL },
						 { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1802_compatibility_entry, NULL },
						 { RW, uint16,  sizeof (UNS16), (void*)&TestMaster_obj1802_event_time, NULL },
					 };
					 
/* index 0x1803 :   TPDO 4 .    Index 1803h-19FFh,  Transmit PDO Communication Parameter  
										 当我需要配置其他节点的字典值时，我变成了客户端，要求服务器自己修改自己*/ 
					UNS8 ClientNumber_0x1803 = 5;
					UNS32 TestMaster_obj1803_COB_ID_PDO = 0x40000186;//服务器，也就是需要修改的节点
					UNS8 TestMaster_obj1803_Transmiss_Type  = TRANS_EVERY_N_SYNC(1);
					UNS16 TestMaster_obj1803_Inhibit_time = 10;
					UNS8 TestMaster_obj1803_compatibility_entry = 0;
					UNS16 TestMaster_obj1803_event_time  = 0;
					subindex TestMaster_Index1803[] = 
					 {
						 { RO, uint8,  sizeof (UNS8), (void*)&ClientNumber_0x1803, NULL },
						 { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1803_COB_ID_PDO, NULL },
						 { RO, uint8, sizeof (UNS8), (void*)&TestMaster_obj1803_Transmiss_Type, NULL },
						 { RW, uint16,  sizeof (UNS16), (void*)&TestMaster_obj1803_Inhibit_time, NULL },
						 { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1803_compatibility_entry, NULL },
						 { RW, uint16,  sizeof (UNS16), (void*)&TestMaster_obj1803_event_time, NULL },
					 };

/* index 0x1804 :   TPDO 4 .    Index 1804h-19FFh,  Transmit PDO Communication Parameter  
										 当我需要配置其他节点的字典值时，我变成了客户端，要求服务器自己修改自己*/ 
					UNS8 ClientNumber_0x1804 = 5;
					UNS32 TestMaster_obj1804_COB_ID_PDO = 0x40000187;//服务器，也就是需要修改的节点
					UNS8 TestMaster_obj1804_Transmiss_Type  = TRANS_EVERY_N_SYNC(1);
					UNS16 TestMaster_obj1804_Inhibit_time = 10;
					UNS8 TestMaster_obj1804_compatibility_entry = 0;
					UNS16 TestMaster_obj1804_event_time  = 0;
					subindex TestMaster_Index1804[] = 
					 {
						 { RO, uint8,  sizeof (UNS8), (void*)&ClientNumber_0x1804, NULL },
						 { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1804_COB_ID_PDO, NULL },
						 { RO, uint8, sizeof (UNS8), (void*)&TestMaster_obj1804_Transmiss_Type, NULL },
						 { RW, uint16,  sizeof (UNS16), (void*)&TestMaster_obj1804_Inhibit_time, NULL },
						 { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1804_compatibility_entry, NULL },
						 { RW, uint16,  sizeof (UNS16), (void*)&TestMaster_obj1804_event_time, NULL },
					 };
					 
/* index 0x1805 :   TPDO 4 .    Index 1805h-19FFh,  Transmit PDO Communication Parameter  
										 当我需要配置其他节点的字典值时，我变成了客户端，要求服务器自己修改自己*/ 
					UNS8 ClientNumber_0x1805 = 5;
					UNS32 TestMaster_obj1805_COB_ID_PDO = 0x40000188;//服务器，也就是需要修改的节点
					UNS8 TestMaster_obj1805_Transmiss_Type  = TRANS_EVERY_N_SYNC(1);
					UNS16 TestMaster_obj1805_Inhibit_time = 10;
					UNS8 TestMaster_obj1805_compatibility_entry = 0;
					UNS16 TestMaster_obj1805_event_time  = 0;
					subindex TestMaster_Index1805[] = 
					 {
						 { RO, uint8,  sizeof (UNS8), (void*)&ClientNumber_0x1805, NULL },
						 { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1805_COB_ID_PDO, NULL },
						 { RO, uint8, sizeof (UNS8), (void*)&TestMaster_obj1805_Transmiss_Type, NULL },
						 { RW, uint16,  sizeof (UNS16), (void*)&TestMaster_obj1805_Inhibit_time, NULL },
						 { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1805_compatibility_entry, NULL },
						 { RW, uint16,  sizeof (UNS16), (void*)&TestMaster_obj1805_event_time, NULL },
					 };
					 
/* 0x1A00  Index 1A00h-1BFFh，Transmit PDO Mapping Parameter */
					UNS8 TestMaster_obj1A00_Number_mapped = 1; //服务器，也就是需要修改的节点
					//UNS32 TestMaster_1_mapped = 0x60400010;
					UNS32 TestMaster_2_mapped = 0x20620020;
                    subindex TestMaster_Index1A00[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_obj1A00_Number_mapped, NULL },
                       //{ RO, uint32, sizeof (UNS32), (void*)&TestMaster_1_mapped, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_2_mapped, NULL },
                     };

/* 0x1A01	 Index 1A01h-1BFFh，Transmit PDO Mapping Parameter */
					 UNS8 TestMaster_obj1A01_Number_mapped = 1; //服务器，也就是需要修改的节点
					 //UNS32 TestMaster_obj1A01_1_mapped = 0x60400010;
					 UNS32 TestMaster_obj1A01_2_mapped = 0x20630020;
					 subindex TestMaster_Index1A01[] = 
					 {
						 { RO, uint8, sizeof (UNS8), (void*)&TestMaster_obj1A01_Number_mapped, NULL },
						 //{ RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A01_1_mapped, NULL },
						 { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A01_2_mapped, NULL },
					 };

/* 0x1A02	 Index 1A02h-1BFFh，Transmit PDO Mapping Parameter */
					 UNS8 TestMaster_obj1A02_Number_mapped = 2; //服务器，也就是需要修改的节点
					 UNS32 TestMaster_obj1A02_1_mapped = 0x60400010;
					 UNS32 TestMaster_obj1A02_2_mapped = 0x20630020;
					 subindex TestMaster_Index1A02[] = 
					 {
						 { RO, uint8, sizeof (UNS8), (void*)&TestMaster_obj1A02_Number_mapped, NULL },
						 { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A02_1_mapped, NULL },
						 { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A02_2_mapped, NULL },
					 };
						 
 /* 0x1A03	 Index 1A03h-1BFFh，Transmit PDO Mapping Parameter */
					 UNS8 TestMaster_obj1A03_Number_mapped = 2; //服务器，也就是需要修改的节点
					 UNS32 TestMaster_obj1A03_1_mapped = 0x60700020;
					 UNS32 TestMaster_obj1A03_2_mapped = 0x607A0020;
					 subindex TestMaster_Index1A03[] = 
					 {
						 { RO, uint8, sizeof (UNS8), (void*)&TestMaster_obj1A03_Number_mapped, NULL },
						 { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A03_1_mapped, NULL },
						 { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A03_2_mapped, NULL },
					 };

 /* 0x1A04	 Index 1A04h-1BFFh，Transmit PDO Mapping Parameter */
					 UNS8 TestMaster_obj1A04_Number_mapped = 2; //服务器，也就是需要修改的节点
					 UNS32 TestMaster_obj1A04_1_mapped = 0x60700020;
					 UNS32 TestMaster_obj1A04_2_mapped = 0x607A0020;
					 subindex TestMaster_Index1A04[] = 
					 {
						 { RO, uint8, sizeof (UNS8), (void*)&TestMaster_obj1A04_Number_mapped, NULL },
						 { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A04_1_mapped, NULL },
						 { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A04_2_mapped, NULL },
					 };
					 
 /* 0x1A05	 Index 1A05h-1BFFh，Transmit PDO Mapping Parameter */
					 UNS8 TestMaster_obj1A05_Number_mapped = 2; //服务器，也就是需要修改的节点
					 UNS32 TestMaster_obj1A05_1_mapped = 0x60700020;
					 UNS32 TestMaster_obj1A05_2_mapped = 0x607A0020;
					 subindex TestMaster_Index1A05[] = 
					 {
						 { RO, uint8, sizeof (UNS8), (void*)&TestMaster_obj1A05_Number_mapped, NULL },
						 { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A05_1_mapped, NULL },
						 { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A05_2_mapped, NULL },
					 };
					 
/* 0x6040   Controlword */
					UNS16 Controlword = 0x0F;//服务器，也就是需要修改的节点
                    subindex TestMaster_Index6040[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Controlword, NULL },
                     };			
										 
/* 0x607A   Target position */
					UNS32 Target_position = 0x1234;//服务器，也就是需要修改的节点
                    subindex TestMaster_Index607A[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Target_position, NULL },
                     };		
					   
/* 0x6060   mode */
					UNS32 mode = 0x6060;//服务器，也就是需要修改的节点
                    subindex TestMaster_Index6060[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&mode, NULL },
                     };
/* 0x6065   mode1 */
				   UNS32 mode1 = 0x6065;//服务器，也就是需要修改的节点
				   subindex TestMaster_Index6065[] = 
					{
					  { RW, uint32, sizeof (UNS32), (void*)&mode1, NULL },
					}; 

/* 0x6070	mode2 */
					UNS32 mode2 = 0x6070;//服务器，也就是需要修改的节点
					subindex TestMaster_Index6070[] = 
					 {
					   { RW, uint32, sizeof (UNS32), (void*)&mode2, NULL },
					 }; 

/* 0x6075	 mode3 */
					 UNS32 mode3 = 0x6075;//服务器，也就是需要修改的节点
					 subindex TestMaster_Index6075[] = 
					  {
						{ RW, uint32, sizeof (UNS32), (void*)&mode3, NULL },
					  }; 
/* 0x6080	mode4 */
					UNS32 mode4 = 0x6080;//服务器，也就是需要修改的节点
					subindex TestMaster_Index6080[] = 
					 {
					   { RW, uint32, sizeof (UNS32), (void*)&mode4, NULL },
					 }; 
/*0x2062 */
					INTEGER32 Pos_SET_VALUE = 0x0;//服务器，也就是需要修改的节点
					subindex TestMaster_Index2062[] =
					 {
					   { RW, int32, sizeof (INTEGER32), (void*)&Pos_SET_VALUE, NULL },
					 };

/* 0x6041   Status */
					UNS16 Statusword = 0x00;//服务器，也就是需要修改的节点
					subindex TestMaster_Index6041[] =
					 {
					   { RW, uint16, sizeof (UNS16), (void*)&Statusword, NULL },
					 };
/* 0x6064   Pos_Actual_Val */
					INTEGER32 Pos_Actual_Val = 0x00;//服务器，也就是需要修改的节点
					subindex TestMaster_Index6064[] =
					 {
					   { RW, int32, sizeof (INTEGER32), (void*)&Pos_Actual_Val, NULL },
					 };

/*0x2063 */
					INTEGER32 Pos_SET_VALUE_node3 = 0x0;//服务器，也就是需要修改的节点
					subindex TestMaster_Index2063[] =
					 {
					   { RW, int32, sizeof (INTEGER32), (void*)&Pos_SET_VALUE_node3, NULL },
					 };

/* 0x6063   Pos_Actual_Val for node3*/
					INTEGER32 Pos_Actual_Val_node3 = 0x00;//服务器，也就是需要修改的节点
					subindex TestMaster_Index6063[] =
					 {
					   { RW, int32, sizeof (INTEGER32), (void*)&Pos_Actual_Val_node3, NULL },
					 };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable TestMaster_objdict[] = 
{
	{ (subindex*)TestMaster_Index1000,sizeof(TestMaster_Index1000)/sizeof(TestMaster_Index1000[0]), 0x1000},
	{ (subindex*)TestMaster_Index1001,sizeof(TestMaster_Index1001)/sizeof(TestMaster_Index1001[0]), 0x1001},
	{ (subindex*)TestMaster_Index1017,sizeof(TestMaster_Index1017)/sizeof(TestMaster_Index1017[0]), 0x1017},
	{ (subindex*)TestMaster_Index1018,sizeof(TestMaster_Index1018)/sizeof(TestMaster_Index1018[0]), 0x1018},

	{ (subindex*)TestMaster_Index1200,sizeof(TestMaster_Index1200)/sizeof(TestMaster_Index1200[0]), 0x1200},
	{ (subindex*)TestMaster_Index1280,sizeof(TestMaster_Index1280)/sizeof(TestMaster_Index1280[0]), 0x1280},
	{ (subindex*)TestMaster_Index1281,sizeof(TestMaster_Index1281)/sizeof(TestMaster_Index1281[0]), 0x1281},

	{ (subindex*)TestMaster_Index1400,sizeof(TestMaster_Index1400)/sizeof(TestMaster_Index1400[0]), 0x1400},
	{ (subindex*)TestMaster_Index1401,sizeof(TestMaster_Index1401)/sizeof(TestMaster_Index1401[0]), 0x1401},
	{ (subindex*)TestMaster_Index1402,sizeof(TestMaster_Index1402)/sizeof(TestMaster_Index1402[0]), 0x1402},
	{ (subindex*)TestMaster_Index1403,sizeof(TestMaster_Index1403)/sizeof(TestMaster_Index1403[0]), 0x1403},
	{ (subindex*)TestMaster_Index1600,sizeof(TestMaster_Index1600)/sizeof(TestMaster_Index1600[0]), 0x1600},
	{ (subindex*)TestMaster_Index1601,sizeof(TestMaster_Index1601)/sizeof(TestMaster_Index1601[0]), 0x1601},
	{ (subindex*)TestMaster_Index1602,sizeof(TestMaster_Index1602)/sizeof(TestMaster_Index1602[0]), 0x1602},
	{ (subindex*)TestMaster_Index1603,sizeof(TestMaster_Index1603)/sizeof(TestMaster_Index1603[0]), 0x1603},

	{ (subindex*)TestMaster_Index1800,sizeof(TestMaster_Index1800)/sizeof(TestMaster_Index1800[0]), 0x1800},
	{ (subindex*)TestMaster_Index1801,sizeof(TestMaster_Index1801)/sizeof(TestMaster_Index1801[0]), 0x1801},
	{ (subindex*)TestMaster_Index1802,sizeof(TestMaster_Index1802)/sizeof(TestMaster_Index1802[0]), 0x1802},
	{ (subindex*)TestMaster_Index1803,sizeof(TestMaster_Index1803)/sizeof(TestMaster_Index1803[0]), 0x1803},
	{ (subindex*)TestMaster_Index1804,sizeof(TestMaster_Index1804)/sizeof(TestMaster_Index1804[0]), 0x1804},
	{ (subindex*)TestMaster_Index1805,sizeof(TestMaster_Index1805)/sizeof(TestMaster_Index1805[0]), 0x1805},
	
	{ (subindex*)TestMaster_Index1A00,sizeof(TestMaster_Index1A00)/sizeof(TestMaster_Index1A00[0]), 0x1A00},
	{ (subindex*)TestMaster_Index1A01,sizeof(TestMaster_Index1A01)/sizeof(TestMaster_Index1A01[0]), 0x1A01},
	{ (subindex*)TestMaster_Index1A02,sizeof(TestMaster_Index1A02)/sizeof(TestMaster_Index1A02[0]), 0x1A02},
	{ (subindex*)TestMaster_Index1A03,sizeof(TestMaster_Index1A03)/sizeof(TestMaster_Index1A03[0]), 0x1A03},
	{ (subindex*)TestMaster_Index1A04,sizeof(TestMaster_Index1A04)/sizeof(TestMaster_Index1A04[0]), 0x1A04},
	{ (subindex*)TestMaster_Index1A05,sizeof(TestMaster_Index1A05)/sizeof(TestMaster_Index1A05[0]), 0x1A05},

	{ (subindex*)TestMaster_Index6040,sizeof(TestMaster_Index6040)/sizeof(TestMaster_Index6040[0]), 0x6040},
	{ (subindex*)TestMaster_Index607A,sizeof(TestMaster_Index607A)/sizeof(TestMaster_Index607A[0]), 0x607A},
	{ (subindex*)TestMaster_Index6060,sizeof(TestMaster_Index6060)/sizeof(TestMaster_Index6060[0]), 0x6060},
	{ (subindex*)TestMaster_Index6065,sizeof(TestMaster_Index6065)/sizeof(TestMaster_Index6065[0]), 0x6065},
	{ (subindex*)TestMaster_Index6070,sizeof(TestMaster_Index6070)/sizeof(TestMaster_Index6070[0]), 0x6070},
	{ (subindex*)TestMaster_Index6075,sizeof(TestMaster_Index6075)/sizeof(TestMaster_Index6075[0]), 0x6075},
	{ (subindex*)TestMaster_Index6080,sizeof(TestMaster_Index6080)/sizeof(TestMaster_Index6080[0]), 0x6080},

	{ (subindex*)TestMaster_Index2062,sizeof(TestMaster_Index2062)/sizeof(TestMaster_Index2062[0]), 0x2062},
	{ (subindex*)TestMaster_Index6041,sizeof(TestMaster_Index6041)/sizeof(TestMaster_Index6041[0]), 0x6041},
	{ (subindex*)TestMaster_Index6064,sizeof(TestMaster_Index6064)/sizeof(TestMaster_Index6064[0]), 0x6064},
	{ (subindex*)TestMaster_Index2063,sizeof(TestMaster_Index2063)/sizeof(TestMaster_Index2063[0]), 0x2063},
	{ (subindex*)TestMaster_Index6063,sizeof(TestMaster_Index6063)/sizeof(TestMaster_Index6063[0]), 0x6063},
};


const indextable * TestMaster_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode)
{
	(void)d;
	int i;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1017: i = 2;break;
		case 0x1018: i = 3;break;
		
		case 0x1200: i = 4;break;
		
		case 0x1280: i = 5;break;
		case 0x1281: i = 6;break;
		
		case 0x1400: i = 7;break;/* PDO_RCV */
		case 0x1401: i = 8;break;
		case 0x1402: i = 9;break;
		case 0x1403: i = 10;break;
		
		case 0x1600: i = 11;break;/* PDO_RCV_MAP */
		case 0x1601: i = 12;break;
		case 0x1602: i = 13;break;
		case 0x1603: i = 14;break;
		
		case 0x1800: i = 15;break;/* PDO_TRS */
		case 0x1801: i = 16;break;
		case 0x1802: i = 17;break;
		case 0x1803: i = 18;break;
		case 0x1804: i = 19;break;
		case 0x1805: i = 20;break;
		
		case 0x1A00: i = 21;break;/* PDO_TRS_MAP */
		case 0x1A01: i = 22;break;
		case 0x1A02: i = 23;break;
		case 0x1A03: i = 24;break;
		case 0x1A04: i = 25;break;
		case 0x1A05: i = 26;break;
		
		case 0x6040: i = 27;break;
		case 0x607A: i = 28;break;
		case 0x6060: i = 29;break;
		case 0x6065: i = 30;break;
		case 0x6070: i = 31;break;
		case 0x6075: i = 32;break;
		case 0x6080: i = 33;break;

		case 0x2062: i = 34;break;
		case 0x6041: i = 35;break;
		case 0x6064: i = 36;break;
		case 0x2063: i = 37;break;
		case 0x6063: i = 38;break;

		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &(TestMaster_objdict[i]);
}


/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
//PDO 通讯管道的数量，要控制6个EPOS，就需要6个结构体
s_PDO_status TestMaster_PDO_status[6] = 
	{s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,
	s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index TestMaster_firstIndex = {
  4, /* SDO_SVR */
  5, /* SDO_CLT */
  7, /* PDO_RCV */
  11, /* PDO_RCV_MAP */
  15, /* PDO_TRS */
  21 /* PDO_TRS_MAP */
};

const quick_index TestMaster_lastIndex = {
  4, /* SDO_SVR */
  6, /* SDO_CLT */
  8, /* PDO_RCV */
  12, /* PDO_RCV_MAP */
  20, /* PDO_TRS */
  26 /* PDO_TRS_MAP */
};

const UNS16 TestMaster_ObjdictSize = sizeof(TestMaster_objdict)/sizeof(TestMaster_objdict[0]); 

CO_Data TestMaster_Data = CANOPEN_NODE_DATA_INITIALIZER(TestMaster);

